(ns ubergraph.core-test
  (:require [clojure.test :refer :all]
            [ubergraph.core :refer :all]))

(defn vec-edges [g]
  (for [e (edges g) :when (not (mirror-edge? e))] [(src e) (dest e)]))

(deftest simple-graph-test
  (let [g1 (graph [1 2] [1 3] [2 3] 4)
        g2 (graph {1 [2 3] 2 [3] 4 []})
        g3 (graph g1)
        g4 (graph g3 (digraph [5 6]) [7 8] 9)
        g5 (graph)]
    (testing "Construction, nodes, edges"
      (are [expected got] (= expected got)
        #{1 2 3 4} (set (nodes g1))
        #{[1 2] [1 3] [2 3]} (set (vec-edges g1))
        (set (nodes g2)) (set (nodes g1))
        (set (vec-edges g2)) (set (vec-edges g1))
        (set (nodes g3)) (set (nodes g1))
        (set (nodes g3)) (set (nodes g1))
        #{1 2 3 4 5 6 7 8 9} (set (nodes g4))
        #{[1 2][1 3][2 3]
          [5 6] [7 8]} (set (vec-edges g4))
        #{} (set (nodes g5))
        #{} (set (edges g5))
        true (has-node? g1 4)
        true (has-edge? g1 1 2)
        false (has-node? g1 5)
        false (has-edge? g1 4 1)))
    (testing "Successors"
      (are [expected got] (= expected got)
        #{2 3} (set (successors g1 1))
        #{1 2} (set (successors g1 3))
        #{} (set (successors g1 4))
        2 (out-degree g1 1)
        2 (out-degree g1 3)
        0 (out-degree g1 4)))
    (testing "Add & remove"
      (are [expected got] (= expected got)
        #{1 2 3 4 5} (set (nodes (add-nodes g1 5)))
        #{:a :b :c} (set (nodes (add-nodes g5 :a :b :c)))
        #{{:id 1} {:id 2}} (set (nodes (add-nodes g5 {:id 1} {:id 2})))
        #{[1 2]} (set (vec-edges (add-edges g5 [1 2])))
        #{1 2} (set (nodes (remove-nodes g1 3 4)))
        #{[1 2]} (set (vec-edges (remove-nodes g1 3 4)))
        #{1 2 3 4} (set (nodes (remove-edges g1 [1 2] [2 1] [1 3] [3 1])))
        #{[2 3]} (set (vec-edges (remove-edges g1 [1 2] [2 1] [1 3] [3 1])))))))

(deftest simple-digraph-test
  (let [g1 (digraph [1 2] [1 3] [2 3] 4)
        g2 (digraph {1 [2 3] 2 [3] 4 []})
        g3 (digraph g1)
        g4 (digraph g3 (graph [5 6]) [7 8] 9)
        g5 (digraph)
        g6 (transpose g1)]
    (testing "Construction, nodes, edges"
      (are [expected got] (= expected got)
        #{1 2 3 4} (set (nodes g1))
        #{1 2 3 4} (set (nodes g6))
        #{[1 2] [1 3] [2 3]} (set (vec-edges g1))
        #{[2 1] [3 1] [3 2]} (set (vec-edges g6))
        (set (nodes g2)) (set (nodes g1))
        (set (vec-edges g2)) (set (vec-edges g1))
        (set (nodes g3)) (set (nodes g1))
        (set (nodes g3)) (set (nodes g1))
        #{1 2 3 4 5 6 7 8 9} (set (nodes g4))
        #{[1 2] [1 3] [2 3] [5 6] [7 8]} (set (vec-edges g4))
        #{} (set (nodes g5))
        #{} (set (vec-edges g5))
        true (has-node? g1 4)
        true (has-edge? g1 1 2)
        false (has-node? g1 5)
        false (has-edge? g1 2 1)))
    (testing "Successors"
      (are [expected got] (= expected got)
        #{2 3} (set (successors g1 1))
        #{} (set (successors g1 3))
        #{} (set (successors g1 4))
        2 (out-degree g1 1)
        0 (out-degree g1 3)
        0 (out-degree g1 4)
        #{1 2} (set (predecessors g1 3))
        #{} (set (predecessors g1 1))
        2 (in-degree g1 3)
        0 (in-degree g1 1)
        #{1 2} (set (successors g6 3))
        #{} (set (successors g6 1))
        2 (out-degree g6 3)
        0 (out-degree g6 1)))
    (testing "Add & remove"
      (are [expected got] (= expected got)
        #{1 2 3 4 5} (set (nodes (add-nodes g1 5)))
        #{:a :b :c} (set (nodes (add-nodes g5 :a :b :c)))
        #{{:id 1} {:id 2}} (set (nodes (add-nodes g5 {:id 1} {:id 2})))
        #{[1 2]} (set (vec-edges (add-edges g5 [1 2])))
        #{1 2} (set (nodes (remove-nodes g1 3 4)))
        #{[1 2]} (set (vec-edges (remove-nodes g1 3 4)))
        #{1 2 3 4} (set (nodes (remove-edges g1 [1 2] [1 3])))
        #{[2 3]} (set (vec-edges (remove-edges g1 [1 2] [1 3])))))))

(deftest simple-weighted-graph-test
  (let [g1 (graph [1 2 77] [1 3 88] [2 3 99] 4)
        g2 (graph {1 {2 77 3 88} 2 {3 99} 4 []})
        g3 (graph g1)
        g4 (graph g3 (digraph [5 6 88]) [7 8] 9)
        g5 (graph)]
    (testing "Construction, nodes, edges"
      (are [expected got] (= expected got)
        #{1 2 3 4} (set (nodes g1))
        #{[1 2] [1 3] [2 3]} (set (vec-edges g1))
        (set (nodes g2)) (set (nodes g1))
        (set (vec-edges g2)) (set (vec-edges g1))
        (set (nodes g3)) (set (nodes g1))
        (set (nodes g3)) (set (nodes g1))
        #{1 2 3 4 5 6 7 8 9} (set (nodes g4))
        #{[1 2] [1 3] [2 3]
          [5 6] [7 8]} (set (vec-edges g4))
        #{} (set (nodes g5))
        #{} (set (edges g5))
        true (has-node? g1 4)
        true (has-edge? g1 1 2)
        false (has-node? g1 5)
        false (has-edge? g1 4 1)))
    (testing "Successors"
      (are [expected got] (= expected got)
        #{2 3} (set (successors g1 1))
        #{1 2} (set (successors g1 3))
        #{} (set (successors g1 4))
        2 (out-degree g1 1)
        2 (out-degree g1 3)
        0 (out-degree g1 4)))
    (testing "Add & remove"
      (are [expected got] (= expected got)
        #{1 2 3 4 5} (set (nodes (add-nodes g1 5)))
        #{:a :b :c} (set (nodes (add-nodes g5 :a :b :c)))
        #{{:id 1} {:id 2}} (set (nodes (add-nodes g5 {:id 1} {:id 2})))
        #{[1 2]} (set (vec-edges (add-edges g5 [1 2])))
        #{1 2} (set (nodes (remove-nodes g1 3 4)))
        #{[1 2]} (set (vec-edges (remove-nodes g1 3 4)))
        #{1 2 3 4} (set (nodes (remove-edges g1 [1 2] [2 1] [1 3] [3 1])))
        #{[2 3]} (set (vec-edges (remove-edges g1 [1 2] [2 1] [1 3] [3 1])))))
    (testing "Weight"
      (are [expected got] (= expected got)
        77 (weight g1 1 2)
        77 (weight g2 1 2)
        77 (weight g3 1 2)
        1 (weight g4 6 5) ;This is different from Loom's behavior
        1 (weight g4 7 8)))))

(deftest simple-weighted-digraph-test
  (let [g1 (digraph [1 2 77] [1 3 88] [2 3 99] 4)
        g2 (digraph {1 {2 77 3 88} 2 {3 99} 4 []})
        g3 (digraph g1)
        g4 (digraph g3 (graph [5 6 88]) [7 8] 9)
        g5 (digraph)
        g6 (transpose g1)]
    (testing "Construction, nodes, edges"
      (are [expected got] (= expected got)
        #{1 2 3 4} (set (nodes g1))
        #{1 2 3 4} (set (nodes g6))
        #{[1 2] [1 3] [2 3]} (set (vec-edges g1))
        #{[2 1] [3 1] [3 2]} (set (vec-edges g6))
        (set (nodes g2)) (set (nodes g1))
        (set (vec-edges g2)) (set (vec-edges g1))
        (set (nodes g3)) (set (nodes g1))
        (set (nodes g3)) (set (nodes g1))
        #{1 2 3 4 5 6 7 8 9} (set (nodes g4))
        #{[1 2] [1 3] [2 3] [5 6] [7 8]} (set (vec-edges g4))
        #{} (set (nodes g5))
        #{} (set (edges g5))
        true (has-node? g1 4)
        true (has-edge? g1 1 2)
        false (has-node? g1 5)
        false (has-edge? g1 2 1)))
    (testing "Successors"
      (are [expected got] (= expected got)
        #{2 3} (set (successors g1 1))
        #{} (set (successors g1 3))
        #{} (set (successors g1 4))
        2 (out-degree g1 1)
        0 (out-degree g1 3)
        0 (out-degree g1 4)
        #{1 2} (set (predecessors g1 3))
        #{} (set (predecessors g1 1))
        2 (in-degree g1 3)
        0 (in-degree g1 1)
        #{1 2} (set (successors g6 3))
        #{} (set (successors g6 1))
        2 (out-degree g6 3)
        0 (out-degree g6 1)))
    (testing "Add & remove"
      (are [expected got] (= expected got)
        #{1 2 3 4 5} (set (nodes (add-nodes g1 5)))
        #{:a :b :c} (set (nodes (add-nodes g5 :a :b :c)))
        #{{:id 1} {:id 2}} (set (nodes (add-nodes g5 {:id 1} {:id 2})))
        #{[1 2]} (set (vec-edges (add-edges g5 [1 2])))
        #{1 2} (set (nodes (remove-nodes g1 3 4)))
        #{[1 2]} (set (vec-edges (remove-nodes g1 3 4)))
        #{1 2 3 4} (set (nodes (remove-edges g1 [1 2] [1 3])))
        #{[2 3]} (set (vec-edges (remove-edges g1 [1 2] [1 3])))))
    (testing "Weight"
      (are [expected got] (= expected got)
        77 (weight g1 1 2)
        77 (weight g2 1 2)
        77 (weight g3 1 2)
        77 (weight g6 2 1)
        88 (weight g4 6 5)
        1 (weight g4 7 8)))))

(deftest graph-with-self-cycles
  (let [g1 (graph [1 1])
        g2 (digraph [1 1])
        g3 (multigraph [1 1 {:color :red}] [1 1 {:color :blue}])
        g4 (multidigraph [1 1 {:color :red}] [1 1 {:color :blue}])]
    (testing "Undirected graph"
      (are [expected got] (= expected got)
        #{1} (set (successors g1 1))
        #{1} (set (predecessors g1 1))
        2 (out-degree g1 1)
        2 (in-degree g1 1)))
    (testing "Directed graph"
      (are [expected got] (= expected got)
        #{1} (set (successors g2 1))
        #{1} (set (predecessors g2 1))
        1 (out-degree g2 1)
        1 (in-degree g2 1)))
    (testing "Multigraph"
      (are [expected got] (= expected got)
        #{1} (set (successors g3 1))
        #{1} (set (predecessors g3 1))
        4 (out-degree g3 1)
        4 (in-degree g3 1)))
    (testing "Multidigraph"
      (are [expected got] (= expected got)
        #{1} (set (successors g4 1))
        #{1} (set (predecessors g4 1))
        2 (out-degree g4 1)
        2 (in-degree g4 1)))))

(deftest ubergraph-constructor
  (let [ug1 (ubergraph true true [1 2]),
        g1 (multigraph [1 2])
        ug2 (ubergraph true false [1 2]),
        g2 (multidigraph [1 2])
        ug3 (ubergraph false true [1 2])
        g3 (graph [1 2])
        ug4 (ubergraph false false [1 2])
        g4 (digraph [1 2])]
    (are [expected got] (= expected got)
         g1 ug1
         g2 ug2
         g3 ug3
         g4 ug4
         [true true false false] (map allow-parallel-edges? [ug1 ug2 ug3 ug4])
         [true false true false] (map undirected-graph? [ug1 ug2 ug3 ug4]))))
